version: '3.8'

services:
  webapi:
    image: Aspnet/webapi:1.0.2
    container_name: aspnet-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=finshark;User Id=sa;Password=AHMADhafidz1312;Encrypt=False;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=AHMADhafidz1312
      - ACCEPT_EULA=Y
